name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor WebAssembly
        run: dotnet publish SketchArchive.csproj -c Release -o release --nologo
        working-directory: .

      - name: Debug Git Status
        run: |
            git status
            git config --list

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          publish_dir: release/wwwroot
          publish_branch: gh-pages
          clean: true
          
 